export const GET_CANDIDATES_REQUEST = 'GET_CANDIDATES_REQUEST';
export const GET_CANDIDATES_SUCCESS = 'GET_CANDIDATES_SUCCESS';
export const GET_CANDIDATES_FAILURE = 'GET_CANDIDATES_FAILURE';

export const ADD_CANDIDATE_REQUEST = 'ADD_CANDIDATE_REQUEST';
export const ADD_CANDIDATE_SUCCESS = 'ADD_CANDIDATE_SUCCESS';
export const ADD_CANDIDATE_FAILURE = 'ADD_CANDIDATE_FAILURE';


export const DELETE_CANDIDATE_REQUEST = 'DELETE_CANDIDATE_REQUEST';
export const DELETE_CANDIDATE_SUCCESS = 'DELETE_CANDIDATE_SUCCESS';
export const DELETE_CANDIDATE_FAILURE = 'DELETE_CANDIDATE_FAILURE';

export const CREATE_CANDIDATE_SURVEY_REQUEST = 'CREATE_CANDIDATE_SURVEY_REQUEST';
export const CREATE_CANDIDATE_SURVEY_SUCCESS = 'CREATE_CANDIDATE_SURVEY_SUCCESS';
export const CREATE_CANDIDATE_SURVEY_FAILURE = 'CREATE_CANDIDATE_SURVEY_FAILURE';

export const SEND_CANDIDATE_EMAIL_REQUEST= 'SEND_CANDIDATE_EMAIL_REQUEST';
export const SEND_CANDIDATE_EMAIL_SUCCESS= 'SEND_CANDIDATE_EMAIL_SUCCESS';
export const SEND_CANDIDATE_EMAIL_FAILURE= 'SEND_CANDIDATE_EMAIL_FAILURE';

